### PR TITLE
Sprint 6

### PR DESCRIPTION
**Pull request by asigdel29**
Tasks:
Professor can create team, 
Professor can edit team 
Professor can edit and set grades

### CODE REVIEW

**Review by daltamur — COMMENTED** [review]
This seems to require a professor adds at least one student to a team upon initial creation, thus disallowing teams to be initially empty. I was under the assumption they had to be able to make completely empty teams, but if the ticket prescribed making a team with one initial student, this seems fine

**Comment by asigdel29** [comment]
> I was also under the same impression , after talking to Danni, I was told that is not the case, In the case that empty teams need to be created the constructor I have created in TeamDAO will take care of that all while working with the original createTeam function

**Comment by daltamur** [comment]
> > I was also under the same impression , after talking to Danni, I was told that is not the case, In the case that empty teams need to be created the constructor I have created in TeamDAO will take care of that all while working with the original createTeam function

Got it, this seems good then

**Review by Kayyali78 — APPROVED** [review]
Agree that the changes are appropriate to ticket and previous conversations regarding change to the TeamDAO and method calls

**Pull request merged**
